version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.x
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt
  pre_build:
    commands:
      - echo "Preparing for build..."
  build:
    commands:
      - echo "Running tests..."
      - pytest --junitxml=reports/results.xml --tb=short
  post_build:
    commands:
      - echo "Build completed successfully!"
artifacts:
  files: 
    - '**/*'
  base-directory: .
reports:
  pytest_report:
    files:
      - "reports/results.xml"
    discard-paths: yes   